### ISSUE TITLE
Feature: size optimization

### ISSUE THREAD

**Issue by Xikaro** [Tau-ri-Dev/JSGMod-1.12.2#174]
Hello, is it possible to reduce the mod? in size, for example, to compress textures so that it fits into 100MB? I ask this because git ghvybvftn, more than 100mb files, and this is important for the development of the modpack, and makes life easier

┆Issue is synchronized with this [Trello card](https://trello.com/c/zRW5oBYz) by [Unito](https://www.unito.io)

**Comment by HDL34** [comment]
We have a site allowing to compress png without quality loss and jpeg without too much quality loss.
So the mod will be less big. But anyway, it will still grow with all the additions.

**Comment by Xikaro** [comment]
No, the folder itself occupies 96mb, I would like, if possible, to reduce the size of the mod, compress the textures, the original mod weighs 23mb, of which 15mb are the textures themselves

**Comment by HDL34** [comment]
by compressing the textures too much you will strongly damage them. Don't forget that the original mod doesn't have the animated event horizon texture. Which alone weighs 5 to 8 MB. Combined with the kawoosh texture for unstable, we are already at 26 MB + all the rest of the textures. You can always try to compress with this but you won't gain much: https://compresspng.com/fr/
For png textures, the loss of quality due to compression will hardly be visible. On the other hand, for jpeg textures, it will be quite visible with a lot of artifact. Especially if the texture has a small resolution. It is even more obvious.
After me I don't care. It's your choice to have crappy textures spoiled by compression and artifacts.

**Comment by MineDragonCZ** [comment]
> No, the folder itself occupies 96mb, I would like, if possible, to reduce the size of the mod, compress the textures, the original mod weighs 23mb, of which 15mb are the textures themselves

Main part of that size is that we copied 3 times the event horizon texture to make the loading faster. So thats basicaly why its that big.
