### ISSUE TITLE
Bug: Disappearing Control Crystals (Milkyway)

### ISSUE THREAD

**Issue by craft90** [Tau-ri-Dev/JSGMod-1.12.2#194]
**Describe the bug**
I recently updated to the latest version of JSG (4.10.1.1) and continued on a already existing world. The first thing I noticed was that the Stargates recorded in my OC program showed up as "missing". I headed over to one to check what the problem was. I noticed the following things:
The DHD was missing its control crystal.
The Stargate was missing its capacitors and glyph crystals.

Once I had replaced those the Stargate functioned as expected.

However the bug affected all of my Stargates in the save. But worst yet, it also affected newly generated random Stargates. Those that you found around the world. So far I've found two with the issue.

I did some further testing and it would appear that on a new save things generated properly. Both the "wild" gates and the Mysterious Page one.

**Mod version**
jsg-1.12.2-4.10.1.1

I'm not sure if you can call it a bug or just an upgrade hiccup. Is there a way to fix my old save or do I just have to deal with it?

**Comment by Fredyman95** [comment]
Hello,
We know about this issue. We must changed mod ID - because mod name was changed, This mod was fork of mod called Aunis. So we must change also mod ID. We made all what we could to reduce this problem to minimum. Unfortunately some actions must be done also by mod user e.g rename of previous configs, rename network file... Specialy network file - this file contain information of all generated gates.

And because mod after update delete old items, blocks... and replace it with new one. Sometimes can happend that you lost items and liquids that were inserted in machines.

**Comment by craft90** [comment]
Thank you for letting me know. I checked the configs and I'd have both the old Aunis configs and the new JSG ones. I renamed the old configs. I'd look around for that network file you mentioned. But I haven't found it. Where is it located?

**Comment by MineDragonCZ** [comment]
> Thank you for letting me know. I checked the configs and I'd have both the old Aunis configs and the new JSG ones. I renamed the old configs. I'd look around for that network file you mentioned. But I haven't found it. Where is it located?

Its located in your world save folder under data folder
`saves/<world>/data`
