### ISSUE TITLE
Feature: Universe Gate Addresses Group

### ISSUE THREAD

**Issue by lukasz4444** [Tau-ri-Dev/JSGMod-1.12.2#225]
**Is your feature request related to a problem? Please describe.**
No it isn't.

**Describe the solution you'd like**
Please add in jsgDimensions.json dimensions group called universeov or something like that. 
Basically the idea is that you need to put 9 chevrons in order to dial any gate that is in dimension contained in group, otherwise dialing would fail, exception to that rule would be if one stargate in that group would dial to another gate that is in same group.

**Comment by Fredyman95** [comment]
In same dimension you need to dial 6 symbols + PoO when you dialing same type of stargate

7 symbols + PoO are requied to dial PG - MW or cross dimension/ dimension group

And 

8 symbols + PoO to establish connection between MW - UNI or PG - UNI stargates

So this your suggestion doesnt make any sence, because in show 9 symbol address is fixed address (address is not affected by position in space)
