### ISSUE TITLE
Bug: Uni Gate Breaking after dialing to the End

### ISSUE THREAD

**Issue by ConnorVex** [Tau-ri-Dev/JSGMod-1.12.2#250]
**Describe the bug**
When Dialing to another dimension using the Universe Gate, it breaks and gets stuck in the 'open' stage but with no portal rendered. Auto Close won't work and becomes unusable unless you destroy the gate block. (Very rarely the entire server will crash)
(This appears to occur in the End City)

**To Reproduce**
1. Create 2 gates, one in the End(End City to be exact) and in the Overworld
2. Dial the Uni gate from the Overworld Into the End City or the other way around
3. go through the gate
4. You will see that the gate is broken, and going way beyond the open time

**Expected behavior**
I expected the gates to function properly, and to close on their own

**Screenshots**
![2023-05-27_23 55 59](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/79610595/9814f627-6c4b-4a4f-bfce-5e964ac29628)
(Broken Gate Visual)

**Mod version**
jsg-1.12.2-4.11.0.8-client.jar

**Additional context**

**Comment by Fredyman95** [comment]
Well visual looks that is damaged by shaders (common issue...) There are some compatible shaders. Just ask in our discord.

About the universe stargate... do you have crashlog from server? Also log from save where is broken stargate can be helpfull

**Comment by MineDragonCZ** [comment]
Can you send here your modlist and your JSG config folder (as .zip)?

**Comment by MineDragonCZ** [comment]
Also does /sgcloseall command work?

**Comment by ConnorVex** [comment]
@Fredyman95 I thought so too, however the gate appeared to remain open no matter what. The Timer was ticking up and it even surpassed 1 minute, so it was open but it wasn't closing on its own

Here goes the Crash log from the server:
[crash-2023-05-27_22.36.18-server.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11587850/crash-2023-05-27_22.36.18-server.txt)


@MineDragonCZ Here goes the information requested:
(Modlist is 235 MB's, here goes a Google Drive Link)
https://drive.google.com/file/d/1EhvNnYcZ_ncQjpoefi6qJQWB4N5PN9yO/view?usp=sharing
(This is server Side, if you want my client side mods too let me know!)

JSG Config:
[JSG Config.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/11587858/JSG.Config.zip)
----
It is worth nothing that after the crash, everything seems to suddenly work again, and repeated attempts to reproduce the bug failed. Before the crash however, it was virtually guaranteed it would occur.

**Comment by MineDragonCZ** [comment]
Does the broken gate close after it reach maximum open time limit? (by your config 4 minutes)

**Comment by ConnorVex** [comment]
I am unsure as the server killed itself after a minute, I have a video of the goof occurring if that helps, would you like it?

**Comment by ConnorVex** [comment]
Updating the Issue:

It appears that this issue occurs whenever Dimension Travel is in the picture, as I jumped from the Nether to the Overworld using the Uni gate, and it broke again. Here goes a video of the [bug in action.
](https://www.veed.io/view/c7a9c5b4-f010-4766-8298-75cf7e286201?sharingWidget=true&panel=share)
I have attempted your fix with the gate close command, however the mod isn't classifying it as 'open' yet it is classifying it as 'busy'

**Comment by ConnorVex** [comment]
Updating this again:
Yes dimension travel is now confirmed to be what is causing the Uni Gate to bug out like this, I am unsure if it will affect other gates but I can give it a shot

**Comment by MineDragonCZ** [comment]
So, If it's still happening, please use universe dialer and on it is Status mode. It should display current gate state (IDLE/INCOMING/ENGAGED-OUTGOING, etc...), please send here that state

**Comment by ConnorVex** [comment]
> So, If it's still happening, please use universe dialer and on it is Status mode. It should display current gate state (IDLE/INCOMING/ENGAGED-OUTGOING, etc...), please send here that state

Sadly this particular bug is very picky when it comes to deciding when to show itself, after a good like 40-50 minutes of trying it has yet to appear

**Comment by Shibva** [comment]
:/  Ima gonna take a shot in the dark, Dosent the gate on the other end need sufficient power to be accessed? By default the Universe Gate has zero capacitor slots available and physical DHD in the world to provide it power via "cold fusion" to recharge it, and given the recent update and my exploring stuff in creative, I see zero capacitors in the structure itself.

from this, we can note the following:
- Universe Gates by default lack any capacitors
- Universe Gates lack a physical DHD that can be used to generate needed power
- Universe Gates lack any sort of capacitor in the wolrdgen frame to provide it power
In Conclusion: Universe Gates cant realistically hold connections or might even fail to dial due to insufficient internal capacity to allow for a cross-dimensional dial; assuming (if that one Gmod addon is accurate to the actual series itself) that cross-dimension dials require more initial energy to "spark" the gate open. Even then if it could the reserves left over after such would be severely low and as a result of what I listed above would not be able to maintain itself for long.

With that said; Universe Gates generated in world will **only be able to be dialed ONCE if possible and then fail due to the receiving gate lacking any form of power generation/reserves by default capacitor slot configuration, DHD to supply power to in general, and physical capacitor banks placed**


If this is ultimately what is happening, one possible solution is to have world-generated Universe gates to have a "DHD" spawn. While afaik there is no such physical DHD device for a universe gate (the dialer is a handheld); I am aware (from the aforementioned Gmod addon being where I learned of this) that there exists a **Naquada Generator** in the series. The solution would be simple; Either include some capacitors in the world-gen for a Universe Gate or add a Naquada Generator where the DHD for any other gate world-gen would be included to serve as a means for power

This is a bit of a stretch and it might not even be whats happening but id figure I say this just in case; I noted having issues with Universe Gates before and Im unsure if it was just because I was still learning how to do everything or that I got it to start working by allowing a single capacitor to be added in the UI via config

**Comment by ConnorVex** [comment]
> :/ Ima gonna take a shot in the dark, Dosent the gate on the other end need sufficient power to be accessed? By default the Universe Gate has zero capacitor slots available and physical DHD in the world to provide it power via "cold fusion" to recharge it, and given the recent update and my exploring stuff in creative, I see zero capacitors in the structure itself.
> 
> from this, we can note the following:
> 
> * Universe Gates by default lack any capacitors
> * Universe Gates lack a physical DHD that can be used to generate needed power
> * Universe Gates lack any sort of capacitor in the wolrdgen frame to provide it power
> * Any stargate that lack enough power to dial will fail; whether it be on the dialing or receiving end (unconfirmed on my end if power being needed on the receiving end but assuming it is)
> 
> In Conclusion: Universe Gates cant realistically hold connections or might even fail to dial due to insufficient internal capacity to allow for a cross-dimensional dial; assuming (if that one Gmod addon is accurate to the actual series itself) that cross-dimension dials require more initial energy to "spark" the gate open. Even then if it could the reserves left over after such would be severely low and as a result of what I listed above would not be able to maintain itself for long.
> 
> With that said; Universe Gates generated in world will **only be able to be dialed ONCE if possible and then fail due to the receiving gate lacking any form of power generation/reserves by default capacitor slot configuration, DHD to supply power to in general, and physical capacitor banks placed**
> 
> If this is ultimately what is happening, one possible solution is to have world-generated Universe gates to have a "DHD" spawn. While afaik there is no such physical DHD device for a universe gate (the dialer is a handheld); I am aware (from the aforementioned Gmod addon being where I learned of this) that there exists a **Naquada Generator** in the series. The solution would be simple; Either include some capacitors in the world-gen for a Universe Gate or add a Naquada Generator where the DHD for any other gate world-gen would be included to serve as a means for power
> 
> This is a bit of a stretch and it might not even be whats happening but id figure I say this just in case; I noted having issues with Universe Gates before and Im unsure if it was just because I was still learning how to do everything or that I got it to start working by allowing a single capacitor to be added in the UI via config

Wonderful to see the thread still active lol
However I nailed down the issue I believe.

Let me just go ahead and say that you can alter the capacitor thing in the UI(you can have up to 3) and Dimension travel IS possible with Uni Gates
I recently was having huge issues with the gates in the newer version, same issue but on a more wider scale. The moment I removed a mod called 'Server Pauser', everything went normally. 

I believe that for this case, the Server pauser mod I had installed wasn't playing nice with JSG.

Thank you for trying to help though!

**Comment by Shibva** [comment]
> Let me just go ahead and say that you can alter the capacitor thing in the UI(you can have up to 3) 
Yeah I'm aware of that but there's a config setting to determine the number of those slots that are acessable; the Uni gate I have found from playing had a default value of available capacitor slots set to 0; meaning you cant add capacitors into the UI nor will the uni gate generate wtih it.

**Comment by MineDragonCZ** [comment]
You can still power the gate, but I see your point there
Anyway, thanks for resolving the issue on your end and for letting me know that Server Pauser should be marked as incompatible.
