### ISSUE TITLE
Bug: OC abort for PEG DHD dial

### ISSUE THREAD

**Issue by lukasz4444** [Tau-ri-Dev/JSGMod-1.12.2#271]
**Describe the bug**

When dialing by DHD computer can abort dialing **only** when gate is idle.
For example, all symbols that you have pressed on DHD are already inputted.

**To Reproduce**
The easiest way is with UNI gates
1. Have 2 Universe type stargates and computer connected to one of them
2. Dial computer connected gate to second one. (Using Universe Dialer)
3. While dialing is active do on computer
lua
component.stargate.abortDialing() 
5. Universe Stargate is ignoring the command and is dialling anyway.

**Expected behavior**
Gate should shut down because of the abort computer command being used.

**Screenshots**

![bugscreenshot](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/93074713/e8aa4d81-6528-4983-88a2-39251f46583d)

**Mod version**
Server - jsg-1.12.2-4.11.1.0-server.jar
Client - jsg-1.12.2-4.11.1.0-client.jar

**Additional context**
It does work on every type of stargate (Except the Orlin one because of obvious reasons.), so if you spam any symbols on pegasus DHD, you can't abort while **DHD has not yet inputted them to stargate.**
The same is for Milky Way gate type, but you need to be really really fast to see the bug on that gate type.

**My whole JSG config (as .zip)**

Okie dokie here's my test server config with default config but i am sending it anyway.

[jsg.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/12186254/jsg.zip)

**Comment by MineDragonCZ** [comment]
When u dialing with universe dialer, you have to wait few seconds before aborting dialing. So you can not dial and abort it right after dialing started... (the cooldown is there because of UNI gate functionallity and without that gate could break)

About DHD of Peg gate, there is actuall problem, I will look on it. **But note that aborting dialing on PC should be used only when dialing by PC.**
