### ISSUE TITLE
Bug: The game crashes every time I interact with a Stargate Base Block

### ISSUE THREAD

**Issue by tayne-obray** [Tau-ri-Dev/JSGMod-1.12.2#290]
**Describe the bug**
Any interaction with a Stargate Base Block causes the game to crash

**To Reproduce**
Any time that I right or left click on a Base block, no matter what I'm holding (even empy hands), and no matter if the stargate is complete or not, it crashes the game. I can't even break the block in creative mode.

**Expected behavior**
To be able to left or right click on the base block without the game crashing

**Mod version**
jsg-1.12.2-4.11.2.3-client

**Additional context**

**My whole JSG config (as .zip)**
[jsg.zip](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/13315517/jsg.zip)

[crash-2023-11-09_21.18.46-client.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/13315524/crash-2023-11-09_21.18.46-client.txt)
[crash-2023-11-09_21.03.44-client.txt](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/files/13315525/crash-2023-11-09_21.03.44-client.txt)

**Comment by MR-Spagetty** [comment]
i notice that another mod is mentioned in the error by the name of "reskillable" can you try again with that mod disabled/not installed

**Comment by Shibva** [comment]
I am not getting this error but I wonder if there's any correlation to another issue I'm having with the Stargate Base Block 

I have a script that was working before with CT that stores a tag inside of ForgeData and it allows me todo some clever things with the ring blocks to prevent griefing unless you have a special pick specified in my script. Only problem is that with the recent changes since  4.11.2.0 ( 4.11.1.0 being when it was last working), the script continues to function except for the stargate base blocks, causing a NullPointerException Every time I try to read data from it.
![image](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/38770780/6e17e800-713a-4a63-81b9-edf55bcc7310)


I will make a separate report on this just to be safe; figured Id bring it up

**Comment by MineDragonCZ** [comment]
Just do not serialize NBT when stargate is not initialized lol

**Comment by MineDragonCZ** [comment]
its this line actually
![image](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/78699120/7e8494d7-ebec-4a3f-8ec7-8e4c985acfe7)

**Comment by Shibva** [comment]
> its this line actually
> 
> ![image](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/assets/78699120/7e8494d7-ebec-4a3f-8ec7-8e4c985acfe7)
> 
> 

@MineDragonCZ yeah, I talked with someone that took a look at it and located the [same line](https://github.com/Tau-ri-Dev/JSGMod-1.12.2/blob/master/src/main/java/tauri/dev/jsg/tileentity/stargate/StargateAbstractBaseTile.java#L1920) for my issue.


They looked through it and they are saying it might have todo with `gatePosMap` lacking an entry

**Comment by Shibva** [comment]
Using blame I was able to find where this went wrong

https://github.com/Tau-ri-Dev/JSGMod-1.12.2/commit/8856f5e1e4259e47f6691cad50b85cbb6291fb3a this is when the erroring in line was initially introduced.

So something from here caused the NBT to possibly be malformed or something to go wrong
